<?php
namespace App\Command;


use Jan\Component\Console\Command\Command;
use Jan\Component\Console\Input\Contract\InputInterface;
use Jan\Component\Console\Output\Contract\OutputInterface;



/**
 * Class ChangePasswordCommand
 * @package App\Command
 *
 * <Generated By JanFramework>
*/
class ChangePasswordCommand extends Command
{

    /**
     * @var string
    */
    protected $name = 'app:user:change-password';


    /**
     * @var string
    */
    protected $description = 'some description of command ...';


    /**
     * @param InputInterface $input
     * @param OutputInterface $output
     * @return int
    */
    public function execute(InputInterface $input, OutputInterface $output): int
    {
           // put some logic here
           $output->write('You are ready for execution app:user:change-password');

           return Command::SUCCESS;
    }
}