<?php
namespace Jan\Foundation\Command\Module;


use Jan\Component\Console\Command\Command;
use Jan\Component\Console\Input\Contract\InputInterface;
use Jan\Component\Console\Output\Contract\OutputInterface;


/**
 * Class MakeResourceCommand
 *
 * @package Jan\Foundation\Command\Module
*/
class MakeResourceCommand extends Command
{

    /**
     * @var string
    */
    protected $name = 'capsule:database:create';


    public function execute(InputInterface $input, OutputInterface $output)
    {
        parent::execute($input, $output); // TODO: Change the autogenerated stub
    }
}