<?php
namespace App\Http\Controller\Admin;


use Jan\Component\Http\Request\Request;
use Jan\Component\Http\Response\Response;
use Jan\Foundation\Routing\Controller;


/**
 * Class NewsController
 * @package App\Http\Controller\Admin
 *
 * <Generated By JanFramework>
*/
class NewsController extends Controller
{

     /**
      * @param Request $request
      * @return Response
     */
     public function index(Request $request): Response
     {
           return new Response('Welcome to NewsController');
     }
}